http:
  routers:
    router-app-authors:
      entryPoints:
        - http
      service: service-app-authors
      #rule: Host(`authors.distribuida.com`)
      rule: PathPrefix(`/app-authors`)
      middlewares:
        - mid-authors
    router-app-books:
      entryPoints:
        - http
      service: service-app-books
      #rule: Host(`authors.distribuida.com`)
      rule: PathPrefix(`/app-books`)
      middlewares:
        - mid-books
  services:
    service-app-authors:
      loadBalancer:
        servers:
          - url: "http://localhost:9090"
    service-app-books:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"
  middlewares:
    mid-authors:
      stripPrefix:
        prefixes:
          - "/app-authors"
    mid-books:
      stripPrefix:
        prefixes:
          - "/app-books"
